/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsBusinessesIndexRouteImport } from './routes/projects/businesses/index'
import { Route as ProjectsProjectSlugIndexRouteImport } from './routes/projects/$projectSlug/index'
import { Route as ProjectsBusinessesProjectSlugIndexRouteImport } from './routes/projects/businesses/$projectSlug/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsBusinessesIndexRoute = ProjectsBusinessesIndexRouteImport.update({
  id: '/projects/businesses/',
  path: '/projects/businesses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectSlugIndexRoute =
  ProjectsProjectSlugIndexRouteImport.update({
    id: '/projects/$projectSlug/',
    path: '/projects/$projectSlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsBusinessesProjectSlugIndexRoute =
  ProjectsBusinessesProjectSlugIndexRouteImport.update({
    id: '/projects/businesses/$projectSlug/',
    path: '/projects/businesses/$projectSlug/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectSlug': typeof ProjectsProjectSlugIndexRoute
  '/projects/businesses': typeof ProjectsBusinessesIndexRoute
  '/projects/businesses/$projectSlug': typeof ProjectsBusinessesProjectSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectSlug': typeof ProjectsProjectSlugIndexRoute
  '/projects/businesses': typeof ProjectsBusinessesIndexRoute
  '/projects/businesses/$projectSlug': typeof ProjectsBusinessesProjectSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectSlug/': typeof ProjectsProjectSlugIndexRoute
  '/projects/businesses/': typeof ProjectsBusinessesIndexRoute
  '/projects/businesses/$projectSlug/': typeof ProjectsBusinessesProjectSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/projects/$projectSlug'
    | '/projects/businesses'
    | '/projects/businesses/$projectSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects'
    | '/projects/$projectSlug'
    | '/projects/businesses'
    | '/projects/businesses/$projectSlug'
  id:
    | '__root__'
    | '/'
    | '/projects/'
    | '/projects/$projectSlug/'
    | '/projects/businesses/'
    | '/projects/businesses/$projectSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsProjectSlugIndexRoute: typeof ProjectsProjectSlugIndexRoute
  ProjectsBusinessesIndexRoute: typeof ProjectsBusinessesIndexRoute
  ProjectsBusinessesProjectSlugIndexRoute: typeof ProjectsBusinessesProjectSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/businesses/': {
      id: '/projects/businesses/'
      path: '/projects/businesses'
      fullPath: '/projects/businesses'
      preLoaderRoute: typeof ProjectsBusinessesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectSlug/': {
      id: '/projects/$projectSlug/'
      path: '/projects/$projectSlug'
      fullPath: '/projects/$projectSlug'
      preLoaderRoute: typeof ProjectsProjectSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/businesses/$projectSlug/': {
      id: '/projects/businesses/$projectSlug/'
      path: '/projects/businesses/$projectSlug'
      fullPath: '/projects/businesses/$projectSlug'
      preLoaderRoute: typeof ProjectsBusinessesProjectSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsProjectSlugIndexRoute: ProjectsProjectSlugIndexRoute,
  ProjectsBusinessesIndexRoute: ProjectsBusinessesIndexRoute,
  ProjectsBusinessesProjectSlugIndexRoute:
    ProjectsBusinessesProjectSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
